# -*- coding: utf-8 -*-
"""Time Series Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jfsmWKu1iVHKBssT4sg0AQlolV_jPoB_

Practicing Time Series Analysis on NASDAQ AAPL
"""

from pandas.tseries.holiday import USFederalHolidayCalendar
from pandas.tseries.offsets import CustomBusinessDay
import pandas as pd 
from google.colab import files

uploaded = files.upload()

#Read Date as time stamp and let the index be Date 
data = pd.read_excel("grid.xls",parse_date= 'Date',index_col= 'Date')
#data.head() 
#data.index
data.shape

#Retrieve Data based on certain date 
data[data.index=='2017-05-30']

#Retrieve Data based on Year(2017)
data['2017':'2018']

#Retrieve Data based on Month(6)
#data['2017-06':'2017-07']
#data['2017-06':'2017-07'].Low
#data['2017-06':'2017-07'].High.mean()
#data['Close'].resample('Year')

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
data['Close'].plot()

"""**Handling holidays and custom calendars**"""

rng = pd.date_range(start='7/1/2017' ,end='7/21/2017',freq='B') #Business frequency 
rng

import pandas as pd
US = CustomBusinessDay(calendar=USFederalHolidayCalendar())

rng = pd.date_range(start="7/1/2017", end="7/30/2017", freq=US)

rng

rng = pd.date_range(start="2017-05-25", end="2018-05-27", freq=US)
data.set_index(rng,inplace=True)
data.head()

"""Retrieving data based on custome freq"""

Arabic_weekmask = 'Sun Mon Tue Wen Thu' 
arab_week = CustomBusinessDay(calendar=Arabic_weekmask)

rng = pd.date_range(start="2017-05-25", end="2018-05-27", freq=arab_week)
rng